In [2]:
import numpy as np

 Q) Create a null vector of size 10 but the fifth value which is 1.

In [24]:
a=np.array([int(x==4) for x in range(10)])
print(a)

[0 0 0 0 1 0 0 0 0 0]


Q) Create a vector with values ranging from 10 to 49.

In [4]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Q) Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
a=np.random.randint(0,8,(3,3))
print(a)

[[1 5 6]
 [7 7 0]
 [3 3 3]]


Q) Find indices of non-zero elements from [1,2,0,0,4,0]

In [22]:
a=np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

Q) Create a 10x10 array with random values and find the minimum and maximum values.

In [17]:
a=np.random.randint(0,10,(10,10))
print(a)
print(a.min())
print(a.max())

[[6 3 7 3 7 0 3 0 6 3]
 [1 3 3 6 6 7 8 4 5 8]
 [2 6 5 4 2 2 0 9 6 0]
 [8 5 0 2 7 5 9 7 9 8]
 [4 4 5 2 7 6 9 9 1 3]
 [6 0 0 9 3 5 8 8 3 3]
 [4 3 2 9 4 6 1 2 1 7]
 [0 7 0 9 2 0 4 0 4 2]
 [3 5 4 7 3 9 4 7 1 1]
 [8 2 6 4 4 7 4 5 1 8]]
0
9


Q) Create a random vector of size 30 and find the mean value.

In [21]:
a=np.arange(0,30)
a.mean()

14.5